import { ThemeProvider } from '@/components/theme-provider';
import type { Metadata } from 'next';
import './globals.css';
import { Header } from '@/components/header';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <ThemeProvider attribute="class" defaultTheme="dark">
          <main
            className="w-full bg-[size:200%_200%]
              bg-gradient-radial
              from-[#c6e4ff]
              to-[#fff7cf]
              animate-background-flow"
          >
            <div
              className="w-full bg-[size:200%_200%] 
              dark:bg-gradient-radial
              from-[#121829]
              to-[#193e63]
              animate-background-flow"
            >
              <Header />
              {children}
            </div>
          </main>
        </ThemeProvider>
      </body>
    </html>
  );
}
