import { ThemeProvider } from '@/components/theme-provider';
import type { Metadata } from 'next';
import './globals.css';
import { Header } from '@/components/header';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <ThemeProvider attribute="class" defaultTheme="light">
          <main
            className="w-full bg-[size:150%_150%]
              bg-gradient-radial
              from-[#b3dcff]
              via-[#b6fbff]
              to-[#fff2b0]
              animate-background-flow"
          >
            <div
              className="w-full bg-[size:150%_150%] 
              dark:bg-gradient-radial
              from-[#232a3e]
              via-[#2b3956]
              to-[#3a83cd]
              animate-background-flow"
            >
              <Header />
              {children}
            </div>
          </main>
        </ThemeProvider>
      </body>
    </html>
  );
}
